Disable two windows tests that recently started to fail on windows CI when using github actions
Motivation:

Recently we started to see two test fail on windows when we run via github actions. We need to investigate why this started to happen as we didnt change anything. For now let us disable these so we don't affect other PRs.

The failure would be something like this:

```
2021-06-10T09:04:13.7787020Z [ERROR] Failures:
2021-06-10T09:04:13.7788559Z [ERROR]   DnsNameResolverTest.testResolveAllHostNameIpv4:847->testResolveAll0:1051 expected: <localhost/127.0.0.1> but was: <fv-az109-589/10.1.0.8>
2021-06-10T09:04:13.7790681Z [ERROR]   DnsNameResolverTest.testResolveHostNameIpv4:786->testResolve0:810 expected: <localhost/127.0.0.1> but was: <fv-az109-589/10.1.0.8>
```

Modifications:

Disable the two tests for now

Result:

Be able to run PR verification for other code-changes without failures