Disable CleanerJava24 at build time for GraalVM <25 Motivation:
On GraalVM 19 to 24, `java.lang.foreign.Arena` becoming reachable is enough to break linking the native image with `/usr/bin/ld: test-suite-http-server-tck-netty-tests.o:(.data+0xf60): undefined reference to `Java_jdk_internal_misc_ScopedMemoryAccess_closeScope0'`. While `CleanerJava24` does guard any access to the class with a version check and a try catch, these checks cannot be constant folded, so Arena remains reachable.

Modification:

Alter CleanerJava24 so that it can be build-time initialized in native image:

- Remove dependency on PlatformDependent0 when in native image
- Do not initialize logger when in native image

Then, in the native image code path, parse `java.specification.version` manually to ensure we're in 25+ before enabling Arena access.

Update `native-image.properties` to initialize `CleanerJava24` at build time.

Result:

`CleanerJava24` is initialized at build time. Native image sees that Arena is not reachable and the resulting native image links successfully.

Note that native image 25 is broken even with this change for what appears to be an unrelated reason related to Unsafe. I've forwarded this to the native image team.

Note that the `initialize-at-build-time` flag added in this PR actually *does not apply* when using the native image build plugins for maven and gradle, because the shared graalvm-reachability-metadata overrides any configuration in netty-common. To resolve this problem, graalvm-reachability-metadata also needs a patch. I cannot make that patch before this PR however, because making CleanerJava24 build-time initialized *without* this PR actually breaks native image on pre-19 versions too, since the logger cannot be initialized at build time.