Fix loading of epoll native transport .so from java.library.path
Motivation:

On some systems creating a shared lib (xx.so) and loading it into the JVM is prohibited. (e.g. grsecurity hardened linux or systems without executable writable path).

Extracting libnetty-tcnative-linux-....so to a path included in java.library.path works fine but loading libnetty_transport_native_epoll.so fails with this exception:

java.lang.UnsatisfiedLinkError: unsupported JNI version 0xFFFFFFFF required by /.../lib/libnetty_transport_native_epoll.so

During initialization netty_unix_util_parse_package_prefix from netty_unix_util.c is looking for "netty-transport-..." in the name of the library, but the library is named "netty_transport_..."

Modifications:

If netty_unix_util_parse_package_prefix fails to find the library name with "-" it will try again with all "-" replaced by "_".

Result:

Now libnetty_transport_native_epoll.so loads properly if placed in java.library.path.