Make [transport] Bootstrap usable with no netty-resolver on classpath.
Motivation:
Since some address families (e.g. unix sockets) do not need name resolver,
It should be possible to exclude netty-resolver from classpath.

Currently excluding name resolver leads to NoClassDefFoundError: AddressResolverGroup during Bootstrap instantiation.

Modification:

Add disableResolver() method to Bootstrap.

Change BootstrapConfig.resolver() return null if Bootstrap.disableResolver() is called.

Introduce ExternalAddressResolver class to hold AddressResolver related references to avoid NoClassDefFoundError if Bootstrap.disableResolver() called and no netty-resolver is on classpath.

Result:

Bootstrap is usable with no netty-resolver on classpath.