Avoid TCPFastOpen in KQueueCompositeBufferGatheringWriteTest (#16697)
Motivation:
We have seen occasional failures from this test in CI, like:

```
Error:  io.netty.channel.kqueue.KQueueCompositeBufferGatheringWriteTest.testSingleCompositeBufferWrite(TestInfo) -- Time elapsed: 0.045 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <20> but was: <0>
	at io.netty.testsuite.transport.socket.CompositeBufferGatheringWriteTest$3$1.channelInactive(CompositeBufferGatheringWriteTest.java:109)
```

In the test, the server writes a composite buffer with 20 bytes as soon
as a client connects, and the write future has a listener that closes
the channel. I speculate that maybe the close races ahead of the write,
when TFO is enabled. Normally, the kernel should still drain the send
buffer of closed sockets, but maybe there's an interaction with TFO
there.

Modification:
Disable the use of TFO in KQueueCompositeBufferGatheringWriteTest, which
matches its epoll counterpart. Log warnings if an unusual IOException
gets thrown on the client.

Result:
Maybe more stable test.

(cherry picked from commit 38f7a73af5ac7492481fe30e36e30a493e5ed668)