Fix PerMessageDeflateDecoderTest
The `testEmptyFrameDecompression` test would sometimes run before the sibling compression test and cause the reader index to be off, resulting in test failures such as:

```
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:183)
	at io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateEncoderTest.testEmptyFrameCompression(PerMessageDeflateEncoderTest.java:297)
```