Fix API compat issue for users that upgrade from 4.1.x to 4.2.0 (#14120)
Motivation:

One API compat issue was detected by servicetalk. We need to fix it:

```
/home/runner/work/servicetalk/servicetalk/servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsResolverAddressTypes.java:66: error: reference to computeResolvedAddressTypes is ambiguous

        return fromNettyType(DnsNameResolverBuilder.computeResolvedAddressTypes());
                                                   ^
  both method computeResolvedAddressTypes(io.netty.channel.socket.InternetProtocolFamily...) in io.netty.resolver.dns.DnsNameResolverBuilder and method computeResolvedAddressTypes(io.netty.channel.socket.SocketProtocolFamily...) in io.netty.resolver.dns.DnsNameResolverBuilder match
Note: Some input files use or override a deprecated API.
> Task :servicetalk-dns-discovery-netty:compileJava FAILED
```

Modifications:

Rename method to fix compat

Result:

Be able to use 4.2.0 where 4.1.x was used