Prepare for unsafe memory access deprecated for removal
Motivation:
Java 23 will introduce JEP 471 (https://openjdk.org/jeps/471) which deprecates all unsafe memory access methods for removal.

The JEP also starts the removal phase, by introducing a new `--sun-misc-unsafe-memory-access={allow|warn|debug|deny}` command line option.
Initially, unsafe memory access will be allowed, but will in future Java versions produce warnings, and then eventually denying access by default.
When access is denied, then calling the unsafe memory access methods will produce an `UnsupportedOperationException`.

Modification:
Include the value of `--sun-misc-unsafe-memory-access` in the consideration of explicit-no-unsafe computation.
The command line value is available as the `sun.misc.unsafe.memory.access` system property.
If the value is not either "allow" or unspecified, then unsafe is explicitly turned off.

Add many more tests to the unsafe availability, probing for all the unsafe memory access methods we use, and also testing some of them with direct calls.

Result:
We should hopefully not see any warnings, or "NoSuchMethodErrors", in the future.